version: '3.8'

services:
  back:
    build: ./back-end
    container_name: back_moment_test
    depends_on:
      - db
    restart: always
    ports:
      - ${EXPOSED_BACK_PORT}:${BACK_PORT}

  db:
    image: postgres:15.1-alpine
    container_name: db_moment_test
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=moment_test_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  front:
    build: ./front-end
    container_name: front_moment_test
    stdin_open: true
    depends_on:
      - db
      - back
    restart: always
    environment:
      - WDS_SOCKET_PORT=0
    ports:
      - ${EXPOSED_FRONT_PORT}:${FRONT_PORT}



volumes:
  postgres_data: null